### PR TITLE
Use installation as default update location

### LINKED ISSUE #434: s25update.exe downloads files to the wrong location
The normale folder structure is:

./RTTR
./Worlds
./DATA
./GFX
./driver

the s25update.exe is located in ./RTTR/s25update.exe

When you start an update, the s25update.exe starts downloading RTTR to it's own location but should be ../ instead.

So you end up with
./RTTR
./RTTR/RTTR
./RTTR/driver
./DATA
./GFX
./driver

As the rttr.bat tells me, the correct calling would be with parameters, "RTTR\s25update.exe --dir %CD%" - but why is that? It's okay for me to tell an updater where to download it and use the current location if no path is provided but... why don't we put the s25update.exe to the same folder as the s25client.exe? I know there are some .dll dependencies but IMHO it's still worth getting rid of a .bat file just to call the s25update.exe with correct parameters (or tell at least, that --dir should be provided instead of calling the .exe)

### PR DESCRIPTION
**Pull request by Flamefire**
This will close https://github.com/Return-To-The-Roots/s25client/issues/434 by trying to use the default installation structure to find the installation path and update to that path.

@Flow86 Please check if this is correct and merge

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -299,6 +299,20 @@ int main(int argc, char* argv[])
...
+#ifdef _WIN32
+    if(boost::filesystem::exists(workPath.parent_path() / "s25client.exe"))
+        workPath = workPath.parent_path();
+#elif defined(__APPLE__)
+    boost::filesystem::path tmpPath = workPath + "/../../../../../..";
+    if(boost::filesystem::exists(tmpPath / "s25client.app/Contents/MacOS/share/s25rttr/RTTR/s25update"))
+        workPath = tmpPath;
+#else
+    boost::filesystem::path tmpPath = workPath + "/../../..";
+    if(boost::filesystem::exists(tmpPath / "share/s25rttr/RTTR/s25update"))
```
Comment (Flow86) [inline src/main.cpp:312]: thats a bit problematic on linux if its not the "standalone"-variant, dont you think?

Comment (Flamefire) [inline src/main.cpp:312]: Well this is why the checks are done: If the path matches the expected path then take it, else take the updaters directory (as before) Or did I miss something? What is different when it is not the "standalone"-variant? Wouldn't this be caught by the check?

Comment (Flow86) [inline src/main.cpp:312]: you could have complete different "bin-dir" then the rest (but then the updater wont update correctly anyway, so ...)
